### ISSUE TITLE
Cor das aspas e string

### ISSUE THREAD

**Issue by realjcwkm** [JoaoLucasXavier/Attractive-Theme#2]
O conteúdo dentro das aspas da a impressão de ser uma variável ou algo que não está relacionado ao texto do bloco " ", pois a coloração deles são diferentes. No caso ficaria melhor sem o My value: fosse laranja também

![string](https://user-images.githubusercontent.com/43896606/126797870-b090213d-8080-4dd9-8777-9eba6b329cb3.png)

**Comment by JoaoLucasXavier** [comment]
Obrigado pela sugestão.
Melhoria adicionada na versão 7.0.0.
