### ISSUE TITLE
Cor dos parâmetros da função

### ISSUE THREAD

**Issue by realjcwkm** [JoaoLucasXavier/Attractive-Theme#3]
Ao usar um parâmetro, este possui cor diferente em determinados momentos da função. Ex: você declarando como parâmetro da função tem a cor vermelho claro, você usando tem a cor amarelo, da a impressão de ser duas variáveis diferentes.

![parametro](https://user-images.githubusercontent.com/43896606/126798530-e69eaf39-487e-4502-b14e-79866490a3b1.png)

**Comment by JoaoLucasXavier** [comment]
Obrigado pela sugestão. 
Melhoria adicionada na versão 7.0.0.
